Add namespace support for NFS deployment and simple fixes
banzaicloud/pvc-operator pull request #25
Opened 2018-09-20 11:32 UTC by baluchicken

Fixes #24

2018-09-20 13:45 UTC, stoader requested changes

2018-09-20 13:45 UTC, stoader commented on pkg/stub/providers/nfs.go
> +			Namespace: nfsNamespace,
Factor out `nfs-provisioner` into a const as it is used in multiple places.

2018-09-20 15:51 UTC, stoader approved these changes
LGTM

2018-09-21 07:58 UTC, bonifaido approved these changes
LGTM

2018-09-21 08:02 UTC, merged